### ISSUE TITLE
com.aerospike.client.AerospikeException: Error Code 1: Server error

### ISSUE THREAD

**Issue by Laxman-SM** [aerospike/aerospike-server#188]
Hi, i saw this error on my application server suddenly started. after adding new node

com.aerospike.client.AerospikeException: Error Code 1: Server error
	at com.aerospike.client.command.ReadCommand.parseResult(ReadCommand.java:121)
	at com.aerospike.client.command.SyncCommand.execute(SyncCommand.java:56)
	at com.aerospike.client.AerospikeClient.get(AerospikeClient.java:515)
	at com.org.platformapi.service.impl.AerospikeClientServiceImpl.getTaxonomyAttributeMap(AerospikeClientServiceImpl.java:310)
	at com.org.platformapi.service.impl.TaxonomyServiceImpl.<init>(TaxonomyServiceImpl.java:31)
	at com.org.pguser.server.UserManagementServer.start(Server.java:101)
	at comorg.user.Server.main(Server.java:190)

aerospike.log

Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:169) NODE-ID bb961cd5d0a0022 CLUSTER-SIZE 11
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:238)    system-memory: free-kbytes 83661700 free-pct 66
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:252)    in-progress: tsvc-q 0 info-q 0 nsup-delete-q 0 rw-hash 0 proxy-hash 0 tree-gc-q 0
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:274)    fds: proto (160,46445515,46445355) heartbeat (10,17,7) fabric (163,185,22)
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:283)    heartbeat-received: self 0 foreign 466851582
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:307)    early-fail: demarshal 0 tsvc-client 2 tsvc-batch-sub 0 tsvc-udf-sub 0
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:337) {userinfo} objects: all 607231077 master 297687584 prole 290580382
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:395) {userinfo} migrations: remaining (0,24) active (0,0) complete-pct 97.96
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:426) {userinfo} memory-usage: total-bytes 38862788928 index-bytes 38862788928 sindex-bytes 0 used-pct 30.41
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:465) {userinfo} device-usage: used-bytes 155376294272 avail-pct 46 cache-read-pct 0.39
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:540) {userinfo} client: tsvc (0,48) proxy (602,0,17) read (2644952403,0,41,1742711693) write (1493773100,70610930,19) delete (0,0,0,0) udf (0,0,0) lang (0,0,0,0)
Jun 16 2017 05:53:27 GMT: INFO (info): (ticker.c:596) {userinfo} scan: basic (26,47,0) aggr (0,0,0) udf-bg (0,0,0)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:145) histogram dump: {userinfo}-read (4387664096 total) msec
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:162)  (00: 4384303749) (01: 0001403544) (02: 0000856855) (03: 0000390483)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:162)  (04: 0000441509) (05: 0000227132) (06: 0000033895) (07: 0000004801)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:171)  (08: 0000002055) (09: 0000000073)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:145) histogram dump: {userinfo}-write (1564384030 total) msec
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:162)  (00: 1338316380) (01: 0063680672) (02: 0046599072) (03: 0047417710)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:162)  (04: 0040863385) (05: 0021905149) (06: 0005255866) (07: 0000334073)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:162)  (08: 0000011201) (09: 0000000440) (10: 0000000071) (12: 0000000003)
Jun 16 2017 05:53:27 GMT: INFO (info): (hist.c:171)  (13: 0000000008)

cluster status is fine. migration still running on server. any one know what causing this error.

**Comment by Laxman-SM** [comment]
Issue fixed. one of the node on cluster having SSD issue.

Jun 16 2017 06:06:39 GMT: WARNING (drv_ssd): (drv_ssd.c:1217) load_n_bins: failed ssd_read_record()
Jun 16 2017 06:06:39 GMT: WARNING (drv_ssd): (drv_ssd.c:1099) {userinfo} read_ssd: invalid rblock_id <Digest>:0x8b2c57cd050cebdb2fffe2f4c4c855a26c6171a0

so replaced node from cluster, after that all working fine.
