### ISSUE TITLE
/usr/bin/asd: error while loading shared libraries: libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by DardBrinza** [aerospike/aerospike-server#215]
Do not run out of the box

Debian GNU/Linux 9 (stretch)
aerospike-server-community-3.16.0.6-debian8

```
root@local:~# service aerospike status
● aerospike.service - Aerospike Server
   Loaded: loaded (/usr/lib/systemd/system/aerospike.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/aerospike.service.d
           └─aerospike.conf
   Active: failed (Result: exit-code) since Wed 2018-03-07 03:16:46 MSK; 4min 33s ago
  Process: 19959 ExecStopPost=/bin/systemctl stop aerospike_telemetry (code=exited, status=0/SUCCESS)
  Process: 19957 ExecStart=/usr/bin/asd $ASD_OPTIONS --config-file $ASD_CONFIG_FILE --fgdaemon (code=exited, status=127)
  Process: 19953 ExecStartPre=/bin/systemctl start aerospike_telemetry (code=exited, status=0/SUCCESS)
  Process: 19946 ExecStartPre=/usr/bin/asd-systemd-helper (code=exited, status=0/SUCCESS)
 Main PID: 19957 (code=exited, status=127)

Mar 07 03:16:46 ns3051071 systemd[1]: Starting Aerospike Server...
Mar 07 03:16:46 ns3051071 systemd[1]: Started Aerospike Server.
Mar 07 03:16:46 ns3051071 asd[19957]: /usr/bin/asd: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Mar 07 03:16:46 ns3051071 systemd[1]: aerospike.service: Main process exited, code=exited, status=127/n/a
Mar 07 03:16:46 ns3051071 systemd[1]: aerospike.service: Unit entered failed state.
Mar 07 03:16:46 ns3051071 systemd[1]: aerospike.service: Failed with result 'exit-code'.

```
```
root@local:~# asinfo -v STATUS
Traceback (most recent call last):
  File "/opt/aerospike/bin/asadm/asadm.py", line 725, in main
    ssl_context=ssl_context, line_separator=cli_args.line_separator)
  File "/opt/aerospike/bin/asadm/asadm.py", line 501, in execute_asinfo_commands
    raise Exception("Could not connect to node")
Exception: Could not connect to node


asinfo requires asadm (>= 0.1.12), please check asadm version.
```

**Comment by psi-mankoski** [comment]
That build *will* work out of the box on Debian 8, but the crypto library versions have changed on Debian 9. While Aerospike does not currently provide a Debian 9 release, it should work as expected if the open source is built and then run on Debian 9.
