### ISSUE TITLE
Index Error when querying with a filter for empty string

### ISSUE THREAD

**Issue by khernyo** [aerospike/aerospike-server#31]
Running the following query with the java client results in an exception:

``` java
        Statement statement = new Statement();
        statement.setNamespace("test");
        statement.setSetName("set");
        statement.setFilters(Filter.equal("indexedBin", ""));
        client.query(null, statement);
```

The exception:

```
com.aerospike.client.AerospikeException: Error Code 204: Index error
  at com.aerospike.client.query.QueryRecordCommand.parseRecordResults(QueryRecordCommand.java:54)
  at com.aerospike.client.command.MultiCommand.parseResult(MultiCommand.java:59)
  at com.aerospike.client.command.SyncCommand.execute(SyncCommand.java:56)
  at com.aerospike.client.query.QueryExecutor$QueryThread.run(QueryExecutor.java:134)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

Also, aql cannot even parse such a query:

```
aql> select * from test.set where indexedBin = ''
Syntax error near token -  'select * from test.set where indexedBin = ''' 
Type " aql --help " from console or simply "help" from within the aql-prompt. 
```

**Comment by blitzprog** [comment]
I also just recently encountered this problem. Is there a known workaround for aql, to query empty strings?

**Comment by kportertx** [comment]
Maybe this has been fixed? I wasn't able to reproduce this:

```
aql> INSERT INTO test.demo (PK, foo, bar) VALUES ('key1', 123, '')
OK, 1 record affected.

aql> select * from test.demo
+-----+-----+
| foo | bar |
+-----+-----+
| 123 | ""  |
+-----+-----+
1 row in set (0.073 secs)

aql> select * from test.demo where bar = ''
0 rows in set (0.002 secs)

Error: (201) AEROSPIKE_ERR_INDEX_NOT_FOUND

aql> CREATE INDEX bar_index ON test.demo (bar) STRING;
OK, 1 index added.

aql> select * from test.demo where bar = ''
+-----+-----+
| foo | bar |
+-----+-----+
| 123 | ""  |
+-----+-----+
1 row in set (0.026 secs)
```

```
aql --version    
Aerospike Query Client
Version 3.15.0.3
C Client Version 4.2.0
Copyright 2012-2017 Aerospike. All rights reserved.
```

Let us know if this is still a problem, and please provide versions of the tools, clients, and servers that you are using. Thanks.
